### ISSUE TITLE
missing package Pillow in python distribution

### ISSUE THREAD

**Issue by cax21** [trustin/sphinx-binary#2]
suppose an rst document with
.. uml:: mydoc.diag
  :width: 300

run sphinx-maven-plugin
...
  File "C:\projects\sphinx-binary\build\venv\lib\site-packages\sphinx\util\logging.py", line 382, in filter
sphinx.errors.SphinxWarning: plantuml: unsupported scaling attributes: width (install PIL or Pillow)

Warning, treated as error:
plantuml: unsupported scaling attributes: width (install PIL or Pillow)

this happens even if my own distribution of python has Pillow installed
$ pip list | grep Pil
Pillow (4.1.1)

**Comment by trustin** [comment]
Thanks for reporting. Will take a look.

**Comment by trustin** [comment]
Thanks for your patience. Will be fixed in 0.5.0.
