### ISSUE TITLE
Release version with latest Sphinx 

### ISSUE THREAD

**Issue by jakubhava** [trustin/sphinx-binary#7]
Would it be possible to release the binary for the latest Sphinx version? Ideally propagate that version to sphinx gradle plugin as well

Thank you!

**Comment by trustin** [comment]
Thanks for asking. I've just released a new version with the latest Sphinx: https://github.com/trustin/sphinx-binary/releases/tag/v0.8.0

**Comment by jakubhava** [comment]
Thank you!
